# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f59108e6e6c4feb078051eccc702c1a746258c4a052e45db4d5fb62ba80cfdecdc0d5d32f7e008f93b3e85124c06c43173e07865d0bb6e47124b91ff33d125e

test:
  secret_key_base: 25f3e662242748f0ea7adbcf7ba70316e69443bfdfe81e92584b592dec3a00cc8b4d8fc73d3be791dc24cedf620f194b24c2f743aae438a2175e572e1e569584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
